# apt install -y rsync
# ansible-playbook -i inventory.yml playbook.yml
---
- name: Synchronize files to fs
  hosts: radxa
  become: yes

  vars:
    timers: "{{ lookup('fileglob', './fs-root/etc/systemd/system/*.timer', wantlist=True) }}"
    reverse_proxy_user: sshtunnel
    ansible_user_name: ansible

  tasks:
  - name: Install prereq.
    block:
    - name: apt packages
      ansible.builtin.apt:
        upgrade: dist #yes
        update_cache: yes

    - name: apt packages
      ansible.builtin.apt:
        update_cache: no
        state: present
        autoremove: true
        autoclean: false
        name:
        - apt-transport-https
        - arp-scan
        - autossh
        - curl
        - device-tree-compiler # needed for Radxa OS for custom pin selection
        - git
        - i2c-tools
        - libnss-mdns
        - nmap
        - podman
        - python3-flask
        - python3-pip
        - python3-smbus # FIXME this should be python3-smbus2, but Radxa OS uses an old kernel
        - rsync
        - tmux
        - tree
        - tree
        - unzip
        - vim
        #- bridge-utils # not needed, we use systemd-networkd

    - name: gpio and i2c packages
      ansible.builtin.pip:
        break_system_packages: true
        name:
        #- i2cdev
        - gpiod # gpioinfo on shell
        #- OPi.GPIO
        #- rpi.gpio
        #- gpiozero
        #- pigpio 

  - name: Allow user to run rsync as root without password
    become: yes
    ansible.builtin.lineinfile:
      path: /etc/sudoers.d/rsync_root
      line: "{{ansible_user}} ALL=(root) NOPASSWD: /usr/bin/rsync"
      state: present
      create: yes
      mode: '0440'
      validate: '/usr/sbin/visudo -cf %s'

  - name: rsync files
    become: yes
    ansible.posix.synchronize:
      src: ./fs-root/
      dest: /
      recursive: yes
      mode: push # 0644
      archive: yes
      compress: yes
      #rsync_path: "sudo rsync"
      #owner
      #group
    register: sync_result

  - name: Set prereq.
    become: true
    block:
    - name: Set timezone using timedatectl
      community.general.timezone:
        name: Europe/Lisbon

    rescue:
    - name: Link /etc/localtime to the correct zoneinfo
      ansible.builtin.file:
        src: "/usr/share/zoneinfo/Europe/Lisbon"
        dest: /etc/localtime
        state: link
        force: yes

    - name: Write timezone to /etc/timezone
      ansible.builtin.copy:
        content: "Europe/Lisbon\n"
        dest: /etc/timezone
        mode: '0644'

  - name: Set prereq.
    block:
    - name: Ensure Canadian English locale exists because they use ISO datetime
      ansible.builtin.locale_gen:
        name: en_CA.UTF-8
        state: present

    - name: Set system locale to en_CA.UTF-8
      ansible.builtin.lineinfile:
        path: /etc/default/locale
        line: 'LANG=en_CA.UTF-8'
        create: yes

  - name: Setup SSH reverse tunnel
    block:
    - name: Create reverse proxy user
      ansible.builtin.user:
        name: "{{reverse_proxy_user}}"
        system: yes
        create_home: yes
        home: "/home/{{reverse_proxy_user}}"
        shell: /usr/sbin/nologin

    - name: Fix SSH directory permissions
      ansible.builtin.file:
        path: "/home/{{reverse_proxy_user}}/.ssh"
        state: directory
        owner: "{{reverse_proxy_user}}"
        group: "{{reverse_proxy_user}}"
        mode: '0700'

    - name: Generate SSH key for reverse tunnel
      ansible.builtin.openssh_keypair:
        path: "/home/{{reverse_proxy_user}}/.ssh/id_rsa"
        type: rsa # ed25519
        size: 4096
        owner: "{{reverse_proxy_user}}"
        group: "{{reverse_proxy_user}}"
        mode: '0600'

  - name: Run systemd-networkd
    block:
    - name: Enable and start systemd networking services (it is normal to be kicked out and a new IP when switched to br0)
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - systemd-networkd
        - systemd-resolved

    - name: Configure nsswitch hosts line for mDNS + resolved
      ansible.builtin.lineinfile:
        path: /etc/nsswitch.conf
        regexp: '^hosts:'
        line: 'hosts: files mymachines mdns_minimal [NOTFOUND=return] resolve dns myhostname'
        backup: yes

    - name: Reload systemd if files were synchronized
      ansible.builtin.systemd_service:
        daemon_reload: yes
      when: sync_result.changed
    #- name: Reload systemd daemon
    #  command: systemctl daemon-reload

    - name: Enable and start timers
      ansible.builtin.systemd_service:
        name: "{{ item | basename }}"
        enabled: yes
        state: started
      loop: "{{ timers }}"
      when: timers | length > 0

    - name: disable avahi in favor of mdns through systemd networking
      ansible.builtin.systemd_service:
        name: avahi-daemon
        enabled: no
        state: stopped
        masked: yes

    - name: disable bluetooth
      ansible.builtin.systemd_service:
        name: bluetooth
        enabled: no
        state: stopped
        masked: yes

    - name: disable wifi
      ansible.builtin.systemd_service:
        name: wpa_supplicant
        enabled: no
        state: stopped
        masked: yes

    - name: disable NetworkManager (on Radxa OS) in favor of systemd networking
      ansible.builtin.systemd_service: 
        name: NetworkManager
        enabled: no
        state: stopped
        masked: yes
      ignore_errors: true # in case not present (Armbian)

    - name: loose the confusion
      ansible.builtin.apt:
        state: absent
        autoremove: true
        name:
        - ifupdown
        - nano
        - netplan.io
        - network-manager
        - bridge-utils

  - name: secure ssh
    when: false
    block:
    - name: Create ansible user
      ansible.builtin.user:
        name: "{{ ansible_user_name }}"
        shell: /bin/bash
        groups: sudo
        append: yes
        create_home: yes

    - name: Create .ssh directory
      ansible.builtin.file:
        path: "/home/{{ ansible_user_name }}/.ssh"
        state: directory
        owner: "{{ ansible_user_name }}"
        group: "{{ ansible_user_name }}"
        mode: '0700'

    - name: Add public key to authorized_keys (remote host)
      ansible.builtin.authorized_key:
        user: "{{ ansible_user_name }}"
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    - name: Disable SSH password authentication
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
        validate: 'sshd -t -f %s'

    - name: Ensure PubkeyAuthentication is enabled
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PubkeyAuthentication'
        line: 'PubkeyAuthentication yes'
        validate: 'sshd -t -f %s'

    - name: Restart SSH service
      ansible.builtin.service:
        name: ssh
        state: restarted

    # --- Controller-side task (known_hosts) ---
    - name: Add remote host key to controller known_hosts
      delegate_to: localhost
      become: false
      ansible.builtin.known_hosts:
        name: "{{ inventory_hostname }}"
        key: "{{ lookup('pipe', 'ssh-keyscan -H ' + inventory_hostname) }}"
        path: "~/.ssh/known_hosts"


# Why Ansible and not cloud-config/armbian_first_run?
# when you do fire and forget, this first_run makes sense
# however, we want to do rolling updates/increments
# and therefore it's desirable to setup Ansible with a hosts list.
# Do phased roll-outs on changes to test first on one destination device.

#cloud-config
# cloud-init devel schema --config-file cloud-init.yml
# /boot/armbian_first_run.txt
