

# Why Ansible and not cloud-config/armbian_first_run?
# when you do fire and forget, this first_run makes sense
# however, we want to do rolling updates/increments
# and therefore it's desirable to setup Ansible with a hosts list.
# Do phased roll-outs on changes to test first on one destination device.

#cloud-config
# cloud-init devel schema --config-file cloud-init.yml
# /boot/armbian_first_run.txt
