# ansible-playbook -i inventory.yml reverse_proxy.yml

---
- name: Synchronize files to fs
  hosts: reverse_proxy
  become: yes

  vars:
    reverse_proxy_user: sshtunnel
    ansible_user_name: ansible
    timezone: Europe/Amsterdam

  tasks:
  - name: Setup SSH reverse tunnel
    block:
    - name: Create reverse proxy user
      ansible.builtin.user:
        name: "{{reverse_proxy_user}}"
        system: yes
        create_home: yes
        home: "/home/{{reverse_proxy_user}}"
        shell: /usr/sbin/nologin

    - name: Fix SSH directory permissions
      ansible.builtin.file:
        path: "/home/{{reverse_proxy_user}}/.ssh"
        state: directory
        owner: "{{reverse_proxy_user}}"
        group: "{{reverse_proxy_user}}"
        mode: '0700'

    - name: Generate SSH key for reverse tunnel
      ansible.builtin.openssh_keypair:
        path: "/home/{{reverse_proxy_user}}/.ssh/id_rsa"
        type: rsa # ed25519
        size: 4096
        owner: "{{reverse_proxy_user}}"
        group: "{{reverse_proxy_user}}"
        mode: '0600'

  - name: secure ssh
    when: false
    block:
    - name: Add public key to authorized_keys (remote host)
      ansible.builtin.authorized_key:
        user: "{{ ansible_user_name }}"
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    # --- Controller-side task (known_hosts) ---
    - name: Add remote host key to controller known_hosts
      delegate_to: localhost
      become: false
      ansible.builtin.known_hosts:
        name: "{{ inventory_hostname }}"
        key: "{{ lookup('pipe', 'ssh-keyscan -H ' + inventory_hostname) }}"
        path: "~/.ssh/known_hosts"
