
- name: apt packages
  ansible.builtin.apt:
    update_cache: no
    state: present
    autoremove: true
    autoclean: false
    name:
    - exfatprogs
    #- ntfs-3g
    - rsync
    - samba
    - smbclient # smbclient -L localhost -N
