
PermitRootLogin prohibit-password
PasswordAuthentication no
PubkeyAuthentication yes

# You might be tempted to only allow local IPv4 addresses
# but this is already accomplished with NAT
# we allow all local + the reverse proxy this server reaches out to
Match Address 0.0.0.0/0,fd00::/8
    PasswordAuthentication yes
