#!/usr/sbin/nft -f

flush ruleset

# IPv4 is shielded with NAT
# but IPv6 we need to protect explicitly
table ip6 filter {
  chain input {
    type filter hook input priority 0;

    ct state established,related accept
    meta l4proto ipv6-icmp accept
    ip6 saddr fe80::/10 accept

    # either just 'drop' or preceeded with 'counter'
    counter drop
  }
}

# nft add rule ip6 filter input tcp dport 22 ip6 saddr fe80::/10 accept
# nft add rule ip6 filter input tcp dport 22 drop
