[global]
   server min protocol = SMB2
   smb ports = 445 139
   interfaces = lo br0
   bind interfaces only = no

[family]
   path = /mnt
   browseable = yes
   read only = no
   guest ok = yes
   guest only = yes
